name: Maven Package

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Configure GIT
      run: |
        git config --global user.name 'Rakesh Jose Thomas'
        git config --global user.email 'rakesh.thomas@apicasystems.com'
        git fetch
        git checkout main
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Bump version
      run: mvn validate -DbumpPatch
    - name: Commit changes
      run: |
        git add pom.xml
        git commit -m "Bumps version"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
